### ISSUE TITLE
Delete Old Files

### ISSUE THREAD

**Issue by Tass0sm** [Code4Community/platformer#12]
We have many old files which are no longer useful. Try to delete as many of these as possible. The following are some we can definitely delete:

1. Delete `src/interperter.js`
2. Delete the `src/language/` directory

The following could be useful for reading and learning, but they aren't important to the current state of the game:

1. `src/scenes/tutorial-scene.js`
2. `src/scenes/tutorial-ecs-scene.js`
3. `src/scenes/tile-demo-scene.js`
4. `src/scenes/hello-world-scene.js`
5. `src/scenes/ecs-demo-scene.js`

Eventually we'll delete `editor.js`, but we can't do that until we replace the current editor interface code with the functions provided by the C4C editor library.

**Comment by aadit-shah** [comment]
Deleted Old Files
